### ISSUE TITLE
Storybook 5 compatibility

### ISSUE THREAD

**Issue by leepowellcouk** [hipstersmoothie/storybook-addon-react-docgen#13] opened 2019-03-14 11:52 UTC
Does this addon work with Storybook 5? I've got the prop table rendering but there is no output for `propType` or `description`.

**Comment by storywr** [comment] 2019-03-14 16:15
Working for me but the panel stays even after pressing the new close icon

**Comment by hipstersmoothie** [comment] 2019-03-14 16:56
Should still work the same. I switched my teams internal storybook over to v5 during the RCs. 

@leepowellcouk make sure that you are exporting the component as a named component. otherwise it might not pick them up

@storywr I can't reproduce that behavior. All the shortcuts work for me as well.

**Comment by storywr** [comment] 2019-03-14 17:18
Looks like the problem was coming from my imported styles in config. Working fine now, thanks.

**Comment by leepowellcouk** [comment] 2019-03-14 17:20
@hipstersmoothie - Component is exported as named. It picks up the propTypes fine, and whether they're required or not. But fails to complete the description (maybe I'm doing it wrong) and the type (boolen, string, etc).

**Comment by hipstersmoothie** [comment] 2019-03-17 08:09
@leepowellcouk any chance i could view the storybook repo?

**Comment by leepowellcouk** [comment] 2019-03-17 09:18
@hipstersmoothie Sadly I can't share - it's a corporate project in a private repo. However I have just debugged through the `makeTableComponent` component and it seems like there is no `__docgenInfo` property on the type.

**Comment by leepowellcouk** [comment] 2019-03-17 09:25
@hipstersmoothie I've found the issue - it's when a component is wrapped in `forwardRef` it loses the `__docgenInfo`. Not sure if it's anything to do with this: https://github.com/storybooks/storybook/issues/5974

**Comment by mattcosta7** [comment] 2019-03-20 00:52
It seems to be a bit more than just forwardRefs not working

a forwardRef works fine as long as it's only child is a component.  Not when it defines the component too.

Works correctly

```tsx
import * as React from "react";
import { Spinner } from "../../icons/Spinner";
import { ButtonBase, ButtonText, LoadingContainer } from "./styles";
import { ButtonProps } from "./types";

export const Button = ({
  children,
  isLoading,
  variant = "filled",
  px = 3,
  py = 2,
  innerRef,
  ...props
}: ButtonProps) => {
  return (
    <ButtonBase
      as="button"
      variant={variant}
      px={px}
      py={py}
      {...props}
      ref={innerRef}
    >
      <ButtonText isLoading={isLoading}>{children}</ButtonText>
      {isLoading && (
        <LoadingContainer>
          <Spinner height="1em" singleColor />
        </LoadingContainer>
      )}
    </ButtonBase>
  );
};

export default React.forwardRef<
  HTMLButtonElement & HTMLDivElement,
  ButtonProps
>((props, ref) => <Button {...props} innerRef={ref} />);
```

However, defining <Button /> inline fails

**Comment by hipstersmoothie** [comment] 2019-03-20 00:59
PRs welcome :) I'll try to find the issues. Small example repo would be great too. I have not used `forwardRef` all that much so i would need the failing case as well. And if you find any more cases that don't work list them too.

Has this worked before?

**Comment by leepowellcouk** [comment] 2019-03-26 17:27
This is my first use of this addon, so I'm not sure if it worked before. The docgen playground indicates there shouldn't be an issue using forwardRef and creates the documentation correctly. So I'm guessing this is an issue with Storybook.

**Comment by leepowellcouk** [comment] 2019-03-27 13:40
Narrowed this down to an issue with the `babel-plugin-react-docgen` plugin and their `actualNameHandler`. The problem is using an arrow function inside the `forwardRef` call doesn't seem to generate an id they can attach a name to so it exits early. https://github.com/storybooks/babel-plugin-react-docgen/blob/fa170793df1d9065ba4bd25238627a72e55fbcb6/src/index.js#L49

**Comment by leepowellcouk** [comment] 2019-03-27 13:43
https://github.com/storybooks/babel-plugin-react-docgen/issues/67

**Comment by leepowellcouk** [comment] 2019-03-27 15:37
I've created a PR for `babel-plugin-react-docgen` to hopefully fix this, if merged we'll then need to wait for the storybook team to update their dependencies:
https://github.com/storybooks/babel-plugin-react-docgen/pull/68

**Comment by hipstersmoothie** [comment] 2019-03-28 19:39
@leepowellcouk awesome progress on this! thanks for your time and work. 

I use this plugin mainly with typescript so it makes sense why i didn't see this. after all your stuff gets merged I'll create a few examples/tests to make sure this breakage doesn't happen again.

**Comment by hipstersmoothie** [comment] 2019-03-28 20:10
@leepowellcouk looks like it got merged. I think the main repo has auto updates for deps on, so it shouldn't be long.

**Comment by leepowellcouk** [comment] 2019-04-01 12:17
👍

**Comment by snnsnn** [comment] 2019-05-13 05:49
I got this warning on import 'storybook-addon-react-docgen/register':
```

vendors~main.d6f274cf48a5e5ef6e54.bundle.js:132237 Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <Styled(div)>. See https://fb.me/react-warning-keys for more information.
    in PropsTable
    in Unknown
    in Unknown
    in Unknown
    in Unknown (created by Context.Consumer)
    in _default (created by Layout)
    in div (created by Context.Consumer)
    in Styled(div) (created by Panel)
    in Panel (created by Layout)
    in div (created by Context.Consumer)
    in Styled(div) (created by Main)
    in div (created by Context.Consumer)
    in Styled(div) (created by Main)
    in Main (created by Layout)
    in Layout (created by Context.Consumer)
    in WithTheme(Layout) (created by ResizeDetector)
    in ResizeDetector
    in div (created by Context.Consumer)
    in Styled(div)
    in Unknown
    in Unknown (created by ResizeDetector)
    in ResizeDetector
    in Unknown
    in Unknown (created by Manager)
    in ThemeProvider (created by Manager)
    in Manager (created by Context.Consumer)
    in Location (created by QueryLocation)
    in QueryLocation (created by Root)
    in LocationProvider (created by Root)
    in HelmetProvider (created by Root)
    in Root
warningWithoutStack @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:132237
warning @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:132652
validateExplicitKey @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:133642
validateChildKeys @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:133664
createElementWithValidation @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:133797
(anonymous) @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:12350
renderWithHooks @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:99945
mountIndeterminateComponent @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:102027
beginWork @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:102632
performUnitOfWork @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:106319
workLoop @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:106359
renderRoot @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:106442
performWorkOnRoot @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:107349
performWork @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:107261
performSyncWork @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:107235
requestWork @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:107104
scheduleWork @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:106918
enqueueSetState @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:98176
push../node_modules/react/cjs/react.development.js.Component.setState @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:132384
(anonymous) @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:124058
requestAnimationFrame (async)
(anonymous) @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:124055
(anonymous) @ vendors~main.d6f274cf48a5e5ef6e54.bundle.js:124047
```

And this deprication notice:

```
onStory(...) has been replaced with on(STORY_CHANGED, ...)
```

**Comment by hipstersmoothie** [comment] 2019-08-09 19:54
I think that all the issues and warnings are resolved. For any future issues browsers feel free to open a new issue if you feel this isn't the case.

**Closed by hipstersmoothie** 2019-08-09 19:54 UTC
